---
- name: Install nginx
  apt:
    pkg: nginx
    state: present
    update_cache: yes

- name: Add nginx config to sites-available
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ host }}

- name: Add symlink in nginx sites-enabled
  file:
    src: /etc/nginx/sites-available/{{ host }}
    dest: /etc/nginx/sites-enabled/{{ host }}
    state: link
  notify:
    - Restart nginx