- name: Add apt-keys
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ keys }}"

- name: Add apt-repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ repos }}"

- name: Install system packages
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages }}"
